version: "3.8"

services:
  database_entersendmailNode:
    image: postgres
    container_name: entersendmailNode
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=entersendmailNode
    volumes:
      - pgdata:/data/postgres
    networks:
      - app-connect
  app:
    build: .
    volumes:
      - .:/usr/app
    ports:
      - "3000:3000"
    depends_on:
      - database_entersendmailNode
    networks:
      - app-connect

volumes:
  pgdata:
    driver: local

networks:
  app-connect:
