version: "3.8"

services:
  postgres:
    image: postgres
    container_name: entersendmailNode
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=entersendmailNode
    volumes:
      - pgdata:/data/postgres
    networks:
      - default
  app:
    build: .
    container_name: entersendmailApp
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    depends_on:
      - postgres
    networks:
      - default

volumes:
  pgdata:
    driver: local

networks:
  default:
    driver: bridge

